package mortalkombatbversion.GameRules;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import mortalkombatbversion.Human;
import mortalkombatbversion.ImageFixer;
import mortalkombatbversion.ImageFixer;
import mortalkombatbversion.Items;
import mortalkombatbversion.Player;

public class JFrames extends javax.swing.JFrame {
    
    Game game = new Game();
    Human human = null;
    Player enemy = null;
    Items[] items = new Items[3];
    String nameButton = "";

    
    /**
     * Creates new form JFrame
     */
    public JFrames() {
            initComponents();
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    try {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (UnsupportedLookAndFeelException ex) {
                        Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            
            //   UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            try {
                game.ReadFromExcel();
            } catch (IOException ex) {
                Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
            }
            game.WriteToTable(RecordsTable);
            buttonGroup1.add(SmallPoisonHealRB);
            buttonGroup1.add(BigPoisonHealRB);
            buttonGroup1.add(BackFromDeadItemRB);
            items[0]=new Items("Малое зелье лечение",0);
            items[1]=new Items("Большое зелье лечение",0);
            items[2]=new Items("Крест возрождения",0);
   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundFrame = new javax.swing.JFrame();
        BackgroundPanel = new javax.swing.JPanel();
        HumanLabelImg = new javax.swing.JLabel();
        Attack = new javax.swing.JButton();
        Protect = new javax.swing.JButton();
        HumanProgressBar = new javax.swing.JProgressBar();
        EnemyLabelImg = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        MyHealthLabel = new javax.swing.JLabel();
        HealthEnemyLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Items = new javax.swing.JButton();
        ChangeLocationLabel = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        RoundStatus = new javax.swing.JLabel();
        Continue = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        StatusWinner = new javax.swing.JLabel();
        WinnerNameTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        FinishGame = new javax.swing.JButton();
        RecordsTableDialog = new javax.swing.JDialog();
        RecordsTablePanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RecordsTable = new javax.swing.JTable();
        CloseRecordsTable = new javax.swing.JButton();
        WhoWinnerDialog = new javax.swing.JDialog();
        WhoWinnerPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Finish = new javax.swing.JButton();
        ItemsBagDialog = new javax.swing.JDialog();
        ItemsPanel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        SmallPoisonHealRB = new javax.swing.JRadioButton();
        BigPoisonHealRB = new javax.swing.JRadioButton();
        BackFromDeadItemRB = new javax.swing.JRadioButton();
        UseItems = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        SelectedItemErrorDialog = new javax.swing.JDialog();
        UtemErrorPanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        UnavailableItemBottomOK = new javax.swing.JButton();
        ChooseLocationDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        setNLocations = new javax.swing.JButton();
        inputNLocation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InitialPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StartGameBottom = new javax.swing.JButton();
        SeeResTableButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        Attack.setBackground(new java.awt.Color(255, 0, 0));
        Attack.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Attack.setForeground(new java.awt.Color(0, 0, 0));
        Attack.setText("Атаковать");
        Attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackActionPerformed(evt);
            }
        });

        Protect.setBackground(new java.awt.Color(255, 204, 0));
        Protect.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Protect.setForeground(new java.awt.Color(0, 0, 0));
        Protect.setText("Защититься");
        Protect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProtectActionPerformed(evt);
            }
        });

        HumanProgressBar.setBackground(new java.awt.Color(204, 204, 204));
        HumanProgressBar.setForeground(new java.awt.Color(51, 255, 51));
        HumanProgressBar.setMaximum(80);
        HumanProgressBar.setMinimum(-1);

        jProgressBar2.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar2.setForeground(new java.awt.Color(0, 255, 0));
        jProgressBar2.setMinimum(-1);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Damage");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Damage");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("16");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("16");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("0 уровень");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("FIGHT");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MyHealthLabel.setBackground(new java.awt.Color(255, 255, 255));
        MyHealthLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        MyHealthLabel.setForeground(new java.awt.Color(102, 102, 102));
        MyHealthLabel.setText("80/80");

        HealthEnemyLabel.setBackground(new java.awt.Color(255, 255, 255));
        HealthEnemyLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        HealthEnemyLabel.setForeground(new java.awt.Color(102, 102, 102));
        HealthEnemyLabel.setText("80/80");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 92, 31));
        jLabel14.setText("experience");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(128, 92, 31));
        jLabel15.setText("points");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(113, 90, 16));
        jLabel16.setText("0/40");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(113, 90, 16));
        jLabel17.setText("00");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("1 уровень");

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Kitana ");

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Items.setBackground(new java.awt.Color(174, 183, 106));
        Items.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Items.setForeground(new java.awt.Color(0, 0, 0));
        Items.setText("Предметы");
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });

        ChangeLocationLabel.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundPanelLayout.createSequentialGroup()
                                .addComponent(ChangeLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(HealthEnemyLabel)
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                                            .addGap(92, 92, 92)
                                                            .addComponent(jLabel15))
                                                        .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                                            .addGap(111, 111, 111)
                                                            .addComponent(jLabel17)
                                                            .addGap(108, 108, 108)
                                                            .addComponent(jLabel16)))))
                                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                                .addGap(215, 215, 215)
                                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                                .addComponent(EnemyLabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)))
                                        .addComponent(Items, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addComponent(HumanLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26))
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                        .addComponent(HumanProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(MyHealthLabel))
                                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45))
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(360, 360, 360))
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addComponent(Attack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(Protect, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))))))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel19)
                    .addContainerGap(854, Short.MAX_VALUE)))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundPanelLayout.createSequentialGroup()
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChangeLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HumanProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(MyHealthLabel))
                            .addComponent(HealthEnemyLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)))
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(EnemyLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(234, 234, 234))
                                    .addComponent(HumanLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Attack, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                .addComponent(Items, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                            .addComponent(Protect, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundPanelLayout.createSequentialGroup()
                    .addGap(229, 229, 229)
                    .addComponent(jLabel19)
                    .addContainerGap(380, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout BackgroundFrameLayout = new javax.swing.GroupLayout(BackgroundFrame.getContentPane());
        BackgroundFrame.getContentPane().setLayout(BackgroundFrameLayout);
        BackgroundFrameLayout.setHorizontalGroup(
            BackgroundFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundFrameLayout.createSequentialGroup()
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundFrameLayout.setVerticalGroup(
            BackgroundFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(179, 226, 217));

        RoundStatus.setBackground(new java.awt.Color(204, 204, 204));
        RoundStatus.setFont(new java.awt.Font("Comic Sans MS", 1, 42)); // NOI18N
        RoundStatus.setForeground(new java.awt.Color(204, 0, 0));
        RoundStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoundStatus.setText("jLabel18");
        RoundStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Continue.setBackground(new java.awt.Color(114, 218, 142));
        Continue.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Continue.setForeground(new java.awt.Color(0, 0, 0));
        Continue.setText("Дальше");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(Continue, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(RoundStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(RoundStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(Continue, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        StatusWinner.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        StatusWinner.setForeground(new java.awt.Color(255, 0, 0));
        StatusWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusWinner.setText("Победа на вашей стороне");

        WinnerNameTF.setBackground(new java.awt.Color(255, 255, 255));
        WinnerNameTF.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        WinnerNameTF.setForeground(new java.awt.Color(0, 0, 0));
        WinnerNameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WinnerNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WinnerNameTFActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Введите имя своего персонажа для добавления");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("результата в таблицу рекордов");

        FinishGame.setBackground(new java.awt.Color(153, 153, 255));
        FinishGame.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        FinishGame.setForeground(new java.awt.Color(51, 51, 51));
        FinishGame.setText("Закончить игру");
        FinishGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FinishGame)
                .addGap(14, 14, 14))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(StatusWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WinnerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(StatusWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(WinnerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FinishGame, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        RecordsTablePanel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Таблица рекордов");

        RecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Имя", "Количество баллов"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RecordsTable);

        CloseRecordsTable.setBackground(new java.awt.Color(255, 255, 153));
        CloseRecordsTable.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        CloseRecordsTable.setForeground(new java.awt.Color(51, 51, 51));
        CloseRecordsTable.setText("Закрыть");
        CloseRecordsTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseRecordsTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RecordsTablePanelLayout = new javax.swing.GroupLayout(RecordsTablePanel);
        RecordsTablePanel.setLayout(RecordsTablePanelLayout);
        RecordsTablePanelLayout.setHorizontalGroup(
            RecordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecordsTablePanelLayout.createSequentialGroup()
                .addGroup(RecordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CloseRecordsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RecordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RecordsTablePanelLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RecordsTablePanelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        RecordsTablePanelLayout.setVerticalGroup(
            RecordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecordsTablePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CloseRecordsTable, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout RecordsTableDialogLayout = new javax.swing.GroupLayout(RecordsTableDialog.getContentPane());
        RecordsTableDialog.getContentPane().setLayout(RecordsTableDialogLayout);
        RecordsTableDialogLayout.setHorizontalGroup(
            RecordsTableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RecordsTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RecordsTableDialogLayout.setVerticalGroup(
            RecordsTableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RecordsTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        WhoWinnerPanel.setBackground(new java.awt.Color(255, 204, 255));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Победа на вашей стороне");

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("К сожалению, Ваш результат не попал в топ 10");

        Finish.setBackground(new java.awt.Color(153, 153, 255));
        Finish.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Finish.setForeground(new java.awt.Color(51, 51, 51));
        Finish.setText("Закончить игру");
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WhoWinnerPanelLayout = new javax.swing.GroupLayout(WhoWinnerPanel);
        WhoWinnerPanel.setLayout(WhoWinnerPanelLayout);
        WhoWinnerPanelLayout.setHorizontalGroup(
            WhoWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WhoWinnerPanelLayout.createSequentialGroup()
                .addGroup(WhoWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WhoWinnerPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WhoWinnerPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WhoWinnerPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(Finish, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        WhoWinnerPanelLayout.setVerticalGroup(
            WhoWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WhoWinnerPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(Finish, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout WhoWinnerDialogLayout = new javax.swing.GroupLayout(WhoWinnerDialog.getContentPane());
        WhoWinnerDialog.getContentPane().setLayout(WhoWinnerDialogLayout);
        WhoWinnerDialogLayout.setHorizontalGroup(
            WhoWinnerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WhoWinnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WhoWinnerDialogLayout.setVerticalGroup(
            WhoWinnerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WhoWinnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ItemsPanel.setBackground(new java.awt.Color(190, 182, 135));

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Мешок предметов");

        SmallPoisonHealRB.setBackground(new java.awt.Color(190, 182, 135));
        SmallPoisonHealRB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        SmallPoisonHealRB.setForeground(new java.awt.Color(0, 0, 0));
        SmallPoisonHealRB.setText("Малое зелье лечение, 0 шт");
        SmallPoisonHealRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallPoisonHealRBActionPerformed(evt);
            }
        });

        BigPoisonHealRB.setBackground(new java.awt.Color(190, 182, 135));
        BigPoisonHealRB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BigPoisonHealRB.setForeground(new java.awt.Color(0, 0, 0));
        BigPoisonHealRB.setText("Большое зелье лечение, 0 шт");
        BigPoisonHealRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BigPoisonHealRBActionPerformed(evt);
            }
        });

        BackFromDeadItemRB.setBackground(new java.awt.Color(190, 182, 135));
        BackFromDeadItemRB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BackFromDeadItemRB.setForeground(new java.awt.Color(0, 0, 0));
        BackFromDeadItemRB.setText("Крест возрождения, 0 шт");

        UseItems.setBackground(new java.awt.Color(239, 237, 14));
        UseItems.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        UseItems.setForeground(new java.awt.Color(0, 0, 0));
        UseItems.setText("Использовать");
        UseItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ItemsPanelLayout = new javax.swing.GroupLayout(ItemsPanel);
        ItemsPanel.setLayout(ItemsPanelLayout);
        ItemsPanelLayout.setHorizontalGroup(
            ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsPanelLayout.createSequentialGroup()
                .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemsPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BigPoisonHealRB)
                            .addComponent(BackFromDeadItemRB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SmallPoisonHealRB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ItemsPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(UseItems)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        ItemsPanelLayout.setVerticalGroup(
            ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(SmallPoisonHealRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BigPoisonHealRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackFromDeadItemRB)
                .addGap(50, 50, 50)
                .addComponent(UseItems, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ItemsBagDialogLayout = new javax.swing.GroupLayout(ItemsBagDialog.getContentPane());
        ItemsBagDialog.getContentPane().setLayout(ItemsBagDialogLayout);
        ItemsBagDialogLayout.setHorizontalGroup(
            ItemsBagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ItemsBagDialogLayout.setVerticalGroup(
            ItemsBagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        UtemErrorPanel.setBackground(new java.awt.Color(243, 120, 120));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Вы не можете использовать ");

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("этот предмет");

        UnavailableItemBottomOK.setBackground(new java.awt.Color(204, 204, 204));
        UnavailableItemBottomOK.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        UnavailableItemBottomOK.setForeground(new java.awt.Color(51, 51, 51));
        UnavailableItemBottomOK.setText("ОК");
        UnavailableItemBottomOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnavailableItemBottomOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UtemErrorPanelLayout = new javax.swing.GroupLayout(UtemErrorPanel);
        UtemErrorPanel.setLayout(UtemErrorPanelLayout);
        UtemErrorPanelLayout.setHorizontalGroup(
            UtemErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UtemErrorPanelLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(UtemErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UtemErrorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UtemErrorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
            .addGroup(UtemErrorPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(UnavailableItemBottomOK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        UtemErrorPanelLayout.setVerticalGroup(
            UtemErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UtemErrorPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(UnavailableItemBottomOK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout SelectedItemErrorDialogLayout = new javax.swing.GroupLayout(SelectedItemErrorDialog.getContentPane());
        SelectedItemErrorDialog.getContentPane().setLayout(SelectedItemErrorDialogLayout);
        SelectedItemErrorDialogLayout.setHorizontalGroup(
            SelectedItemErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UtemErrorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SelectedItemErrorDialogLayout.setVerticalGroup(
            SelectedItemErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UtemErrorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setNLocations.setText("Start to play");
        setNLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNLocationsActionPerformed(evt);
            }
        });

        inputNLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNLocationActionPerformed(evt);
            }
        });

        jLabel2.setText("Choose N locations = ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(inputNLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(setNLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(setNLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout ChooseLocationDialogLayout = new javax.swing.GroupLayout(ChooseLocationDialog.getContentPane());
        ChooseLocationDialog.getContentPane().setLayout(ChooseLocationDialogLayout);
        ChooseLocationDialogLayout.setHorizontalGroup(
            ChooseLocationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ChooseLocationDialogLayout.setVerticalGroup(
            ChooseLocationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChooseLocationDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InitialPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mortal Kombat");

        StartGameBottom.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        StartGameBottom.setText("Начать новую игру");
        StartGameBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameBottomActionPerformed(evt);
            }
        });

        SeeResTableButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        SeeResTableButton.setText("Посмотреть таблицу \nрезультатов");
        SeeResTableButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        SeeResTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeResTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InitialPanelLayout = new javax.swing.GroupLayout(InitialPanel);
        InitialPanel.setLayout(InitialPanelLayout);
        InitialPanelLayout.setHorizontalGroup(
            InitialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InitialPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SeeResTableButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(StartGameBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(InitialPanelLayout.createSequentialGroup()
                .addGroup(InitialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InitialPanelLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InitialPanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InitialPanelLayout.setVerticalGroup(
            InitialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InitialPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(InitialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeeResTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartGameBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InitialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InitialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartGameBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameBottomActionPerformed
       
        ChooseLocationDialog.setVisible(true);
        ChooseLocationDialog.setBounds(200, 100, 500, 300);
        
      
        
    }//GEN-LAST:event_StartGameBottomActionPerformed

    private void AttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackActionPerformed
        game.fight.Hit(human, enemy, 1, HealthEnemyLabel, MyHealthLabel, jDialog1, 
                RoundStatus, game.action, HumanProgressBar, jProgressBar2, jDialog2, 
                WhoWinnerDialog, BackgroundFrame, game.getResults(), StatusWinner, jLabel24, 
                jLabel26, jLabel29, jLabel27, items, BackFromDeadItemRB,  ChangeLocationLabel, BackgroundPanel);
        
    }//GEN-LAST:event_AttackActionPerformed

    private void ProtectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProtectActionPerformed
        game.fight.Hit(human, enemy, 0, HealthEnemyLabel, MyHealthLabel, jDialog1, 
                RoundStatus, game.action, HumanProgressBar, jProgressBar2, jDialog2, 
                WhoWinnerDialog, BackgroundFrame, game.getResults(), StatusWinner, jLabel24, 
                jLabel26, jLabel29, jLabel27, items, BackFromDeadItemRB,  ChangeLocationLabel, BackgroundPanel);
        
    }//GEN-LAST:event_ProtectActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed

        enemy=game.fight.NewRound(human, EnemyLabelImg, HumanProgressBar, jProgressBar2, 
                jLabel5, jLabel10, HealthEnemyLabel, game.action);

        
        game.change.NewRoundTexts(human, enemy, HumanProgressBar, jProgressBar2, 
                jLabel17, jLabel16, jLabel6, jLabel19, MyHealthLabel, HealthEnemyLabel, jLabel9,
                jLabel26, jLabel27, game.fight.i, items, SmallPoisonHealRB, BigPoisonHealRB, BackFromDeadItemRB);

        jDialog1.dispose();
    }//GEN-LAST:event_ContinueActionPerformed

    private void WinnerNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WinnerNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WinnerNameTFActionPerformed

    private void FinishGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishGameActionPerformed
        try {
            game.EndGameTop(human, WinnerNameTF, RecordsTable);
        } catch (IOException ex) {
            Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialog2.dispose();
        WinnerNameTF.setText("");
    }//GEN-LAST:event_FinishGameActionPerformed

    private void CloseRecordsTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseRecordsTableActionPerformed
        RecordsTableDialog.dispose();
    }//GEN-LAST:event_CloseRecordsTableActionPerformed

    private void SeeResTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeResTableButtonActionPerformed
        RecordsTableDialog.setVisible(true);
        RecordsTableDialog.setBounds(100, 100, 580, 450);
    }//GEN-LAST:event_SeeResTableButtonActionPerformed

    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        WhoWinnerDialog.dispose();
    }//GEN-LAST:event_FinishActionPerformed

    private void SmallPoisonHealRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallPoisonHealRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallPoisonHealRBActionPerformed

    private void BigPoisonHealRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BigPoisonHealRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BigPoisonHealRBActionPerformed

    private void UseItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseItemsActionPerformed
        if(SmallPoisonHealRB.isSelected()){
            nameButton="jRadioButton1";
        }
        if(BigPoisonHealRB.isSelected()){
            nameButton="jRadioButton2";
        }
        if(BackFromDeadItemRB.isSelected()){
            nameButton="jRadioButton3";
        }
        game.action.UseItem(human, items, nameButton, SelectedItemErrorDialog, ItemsBagDialog);
        game.action.HP(human, HumanProgressBar);
        MyHealthLabel.setText(human.getHealth() + "/" + human.getMaxHealth());
        game.change.BagText(items, SmallPoisonHealRB, BigPoisonHealRB, BackFromDeadItemRB);
    }//GEN-LAST:event_UseItemsActionPerformed

    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed
        ItemsBagDialog.setVisible(true);
        ItemsBagDialog.setBounds(300, 200, 430, 350);
    }//GEN-LAST:event_ItemsActionPerformed

    private void UnavailableItemBottomOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnavailableItemBottomOKActionPerformed
        SelectedItemErrorDialog.dispose();
    }//GEN-LAST:event_UnavailableItemBottomOKActionPerformed
    int locations = 0;
  
    ImageFixer imfixer = new ImageFixer();
    
    private void setNLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNLocationsActionPerformed
        // TODO add your handling code here:
        this.locations = Integer.parseInt(inputNLocation.getText());
        ChooseLocationDialog.setVisible(false);
        game.location=this.locations;
          
        BackgroundFrame.setVisible(rootPaneCheckingEnabled);
        BackgroundFrame.setSize(1000,700);
        
        ImageIcon img = new ImageIcon("IMGSource/MainHero.jpg");
        //HumanLabelImg.setIcon(img);
        
        HumanLabelImg.setIcon(imfixer.getScaledImage(img.getImage()));
        
        human = game.NewHuman(HumanProgressBar, this.locations);
       // human.setNLocations(this.locations);
        enemy = game.NewEnemy(EnemyLabelImg, jLabel5, jLabel10, HealthEnemyLabel, jProgressBar2);
          
        game.change.NewRoundTexts(human, enemy, HumanProgressBar, jProgressBar2, 
                jLabel17, jLabel16, jLabel6, jLabel19, MyHealthLabel, HealthEnemyLabel, jLabel9,
                jLabel26, jLabel27, game.fight.i, items, SmallPoisonHealRB, BigPoisonHealRB, BackFromDeadItemRB);
        
        ChangeLocationLabel.setText("");
        
    }//GEN-LAST:event_setNLocationsActionPerformed

    private void inputNLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNLocationActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attack;
    private javax.swing.JRadioButton BackFromDeadItemRB;
    private javax.swing.JFrame BackgroundFrame;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JRadioButton BigPoisonHealRB;
    private javax.swing.JLabel ChangeLocationLabel;
    private javax.swing.JDialog ChooseLocationDialog;
    private javax.swing.JButton CloseRecordsTable;
    private javax.swing.JButton Continue;
    private javax.swing.JLabel EnemyLabelImg;
    private javax.swing.JButton Finish;
    private javax.swing.JButton FinishGame;
    private javax.swing.JLabel HealthEnemyLabel;
    private javax.swing.JLabel HumanLabelImg;
    private javax.swing.JProgressBar HumanProgressBar;
    private javax.swing.JPanel InitialPanel;
    private javax.swing.JButton Items;
    private javax.swing.JDialog ItemsBagDialog;
    private javax.swing.JPanel ItemsPanel;
    private javax.swing.JLabel MyHealthLabel;
    private javax.swing.JButton Protect;
    private javax.swing.JTable RecordsTable;
    private javax.swing.JDialog RecordsTableDialog;
    private javax.swing.JPanel RecordsTablePanel;
    private javax.swing.JLabel RoundStatus;
    private javax.swing.JButton SeeResTableButton;
    private javax.swing.JDialog SelectedItemErrorDialog;
    private javax.swing.JRadioButton SmallPoisonHealRB;
    private javax.swing.JButton StartGameBottom;
    private javax.swing.JLabel StatusWinner;
    private javax.swing.JButton UnavailableItemBottomOK;
    private javax.swing.JButton UseItems;
    private javax.swing.JPanel UtemErrorPanel;
    private javax.swing.JDialog WhoWinnerDialog;
    private javax.swing.JPanel WhoWinnerPanel;
    private javax.swing.JTextField WinnerNameTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField inputNLocation;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton setNLocations;
    // End of variables declaration//GEN-END:variables
}
